### ISSUE TITLE
pip install mongoctl fails on OS X

### ISSUE THREAD

**Issue by niallo** [mongolab/mongoctl#12]
On OS X 10.9.1 (w/ Python 2.7.5), installation of mongoctl fails with pip:

```
sudo pip install mongoctl
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: pip==1.3.1
```

**Comment by abdulito** [comment]
Looks more of an env issue. Please create a new issue if you are still seeing the problem
